/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Luis
 */
public class PanelBanner extends javax.swing.JPanel {

    private LinealProgrammingInterface ui;
    private JFrame actual;
    /**
     * Creates new form PanelBanner
     */
    public PanelBanner(LinealProgrammingInterface ui, JFrame actual) {
        initComponents();
        this.ui = ui;
        this.actual = actual;
        butAdvanced.setBorder(null);
        butAdvanced.setContentAreaFilled(false);
        butBeginner.setBorder(null);
        butBeginner.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butBeginner = new javax.swing.JButton();
        butAdvanced = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butBeginner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butBeginner.setForeground(new java.awt.Color(255, 255, 255));
        butBeginner.setText("Beginner");
        butBeginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBeginnerActionPerformed(evt);
            }
        });
        add(butBeginner, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 110, 40));

        butAdvanced.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butAdvanced.setForeground(new java.awt.Color(255, 255, 255));
        butAdvanced.setText("Advanced");
        butAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAdvancedActionPerformed(evt);
            }
        });
        add(butAdvanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Simplex portada.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void butBeginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBeginnerActionPerformed
        ui.setMode("Beginner");
        ui.setLocationRelativeTo(null);
        ui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ui.setVisible(true);
        ui.setTitle("SIMPOD-Beginner mode");
        actual.setVisible(false);
    }//GEN-LAST:event_butBeginnerActionPerformed

    private void butAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAdvancedActionPerformed
        ui.setMode("Advanced");
        ui.setLocationRelativeTo(null);
        ui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ui.setVisible(true);
        ui.setTitle("SIMPOD-Advanced mode");
        actual.setVisible(false);
    }//GEN-LAST:event_butAdvancedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdvanced;
    private javax.swing.JButton butBeginner;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
